### DISCUSSION TITLE
Cannot run docker-compose: XXX is not allowed to connect to this MySQL server

### DISCUSSION THREAD

**Discussion by SebastianStehle** [infiniflow/ragflow#1275] [Q&A]
Hi,

I am trying to run rag flow with the official docker-compose under Windows.

First i had issues to run the MySQL, but after I added a file sharing resource in Docker Desktop it started fine.

Now I struggle with this issue:

```
ragflow-server  | peewee.OperationalError: (1130, "172.29.0.6' is not allowed to connect to this MySQL server")
```

I added the following line to the docker-compose-base.yml, but so far I have no success:

```
  mysql:
    image: mysql:5.7.18
    container_name: ragflow-mysql
    environment:
      - MYSQL_ROOT_HOST=% <---
```
