### ISSUE TITLE
[Question]: 

### ISSUE THREAD

**Issue by wilac-pv** [infiniflow/ragflow#1463]
### 问题描述

在 macOS 上使用 Docker 和 Docker Compose 启动 MySQL 容器时，出现 `chown: invalid user: 'mysql:mysql'` 错误。

### 环境

- **操作系统**: macOS
- **Docker 版本**: [请提供具体版本]
- **Docker Compose 版本**: [请提供具体版本]
- **MySQL 镜像版本**: mysql:5.7.18

### 错误日志

```plaintext
2024-07-11 14:50:05 chown: invalid user: 'mysql:mysql'
2024-07-11 14:50:12 chown: invalid user: 'mysql:mysql'
```

### Docker Compose 配置

```yaml
version: '3.1'

services:
  mysql:
    image: mysql:5.7.18
    container_name: ragflow-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - TZ=${TIMEZONE}
    command:
      --max_connections=1000
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --default-authentication-plugin=mysql_native_password
      --tls_version="TLSv1.2,TLSv1.3"
      --init-file /data/application/init.sql
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/data/application/init.sql
    networks:
      - ragflow
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uroot", "-p${MYSQL_PASSWORD}"]
      interval: 10s
      timeout: 10s
      retries: 3
    restart: always

volumes:
  mysql_data:
    driver: local

networks:
  ragflow:
    driver: bridge
```

### 排查步骤

1. **确认 MySQL 镜像中的用户和组**:
    - 运行 `docker run -it --rm mysql:5.7.18 /bin/bash`。
    - 检查是否存在 `mysql` 用户和组：
      ```sh
      cat /etc/passwd | grep mysql
      ```

2. **手动创建 MySQL 用户和组**:
    - 如果没有 `mysql` 用户和组，在容器内手动创建：
      ```sh
      groupadd -r mysql && useradd -r -g mysql mysql
      ```

3. **检查数据卷权限**:
    - 确保数据卷的权限正确，在主机系统上更改卷的权限：
      ```sh
      docker run --rm -v ragflow-mysql:/var/lib/mysql busybox chown -R 999:999 /var/lib/mysql
      ```

4. **更新 Docker Compose 文件**:
    - 确保 `docker-compose.yml` 文件中没有手动指定用户或组。

5. **重启 Docker Compose**:
    - 确保所有配置和权限都正确后，重启 Docker Compose 环境：
      ```sh
      docker-compose down
      docker-compose up -d
      ```

6. **检查容器日志**:
    - 查看 MySQL 容器的日志，确认是否有其他错误信息：
      ```sh
      docker logs ragflow-mysql
      ```

### 预期行为

MySQL 容器应正常启动，并且没有 `chown: invalid user: 'mysql:mysql'` 错误。

### 实际行为

启动 MySQL 容器时，出现 `chown: invalid user: 'mysql:mysql'` 错误。

### 其他信息

在执行 `docker run --rm mysql:5.7.18 cat /etc/passwd | grep mysql` 命令时，没有输出。这表明在 MySQL 5.7.18 容器内没有创建 `mysql` 用户。

### 请求的帮助

需要帮助确认 MySQL 官方镜像中的用户和组配置，并解决 `chown: invalid user: 'mysql:mysql'` 错误，使 MySQL 容器能够正常启动。

**目前换到了 mysql最新版本的镜像无问题**
