### ISSUE TITLE
[Question]: Follow the readme, i can not start program by 'bash docker/entrypoint.sh'

### ISSUE THREAD

**Issue by kuschzzp** [infiniflow/ragflow#2617]
### Describe your problem

Here are all the console outputs: 
<img width="995" alt="image" src="https://github.com/user-attachments/assets/6bcb4a25-3c4f-4f0f-825b-9c33ad971d41">

1.  i had set `10.211.55.13   es01 mysql minio redis` to /ect/hosts.   `10.211.55.13` is my virtual machine address。
2. i had update  `entrypoint.sh`
```
        ......
        #/usr/sbin/nginx
        #export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/
        export PYTHONPATH=$(pwd)
        export HF_ENDPOINT=https://hf-mirror.com
        ......
```

environment : `M1 macbook`

**Comment by KevinHuSh** [comment]
code 137.
It's been killed for lack of memory, may be.

**Comment by kuschzzp** [comment]
> code 137. It's been killed for lack of memory, may be.

**The memory is enough, is there a way to display the detailed log**

<img width="101" alt="image" src="https://github.com/user-attachments/assets/a82a6fff-3268-45bb-a36d-da5f5bc6e924">
<img width="1063" alt="image" src="https://github.com/user-attachments/assets/7f6ce245-7612-414a-9121-d416e3aca7b9">

**Comment by yuzhichang** [comment]
M1 MacBook cpu is arm. Which ragflow image are you using?

**Comment by kuschzzp** [comment]
> M1 MacBook cpu is arm. Which ragflow image are you using?

[Launch the RAGFlow Backend Service From Source](https://ragflow.io/docs/dev/launch_ragflow_from_source)

i use this  `docker-compose-base.yml` deploy  es，redis......  on my virtual machine.  **centos9**
```
services:
  es01:
    container_name: ragflow-es-01
    image: elasticsearch:8.11.3
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    environment:
      - node.name=es01
      - ELASTIC_PASSWORD=infini_rag_flow
      - bootstrap.memory_lock=false
      - discovery.type=single-node
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - TZ='Asia/Shanghai'
    mem_limit: 8073741824
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:9200"]
      interval: 10s
      timeout: 10s
      retries: 120
    networks:
      - ragflow
    restart: always

  mysql:
    # mysql:5.7 linux/arm64 image is unavailable.
    image: mysql:8.0.39
    container_name: ragflow-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=infini_rag_flow
      - TZ='Asia/Shanghai'
    command:
      --max_connections=1000
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --default-authentication-plugin=mysql_native_password
      --tls_version="TLSv1.2,TLSv1.3"
      --init-file /data/application/init.sql
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/data/application/init.sql
    networks:
      - ragflow
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-uroot", "-pinfini_rag_flow"]
      interval: 10s
      timeout: 10s
      retries: 3
    restart: always

  minio:
    image: quay.io/minio/minio:RELEASE.2023-12-20T01-00-02Z
    container_name: ragflow-minio
    command: server --console-address ":9001" /data
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=rag_flow
      - MINIO_ROOT_PASSWORD=infini_rag_flow
      - TZ='Asia/Shanghai'
    volumes:
      - minio_data:/data
    networks:
      - ragflow
    restart: always

  redis:
    image: redis:7.2.4
    container_name: ragflow-redis
    command: redis-server --requirepass infini_rag_flow --maxmemory 128mb --maxmemory-policy allkeys-lru
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    networks:
      - ragflow
    restart: always



volumes:
  esdata01:
    driver: local
  mysql_data:
    driver: local
  minio_data:
    driver: local
  redis_data:
    driver: local

networks:
  ragflow:
    driver: bridge

```

**And i follow  `https://ragflow.io/docs/dev/launch_ragflow_from_source `
run by `bash docker/entrypoint.sh`**

**Comment by yuzhichang** [comment]
Show your `docker/.env`

**Comment by yuzhichang** [comment]
Where did you run `bash docker/entrypoint.sh`, on `M1 macbook`, or the linux vm `10.211.55.13`?
We don't have `M1 macbook`. However I confirm that this procedure work on `linux/arm64`.

**Comment by kuschzzp** [comment]
> Where did you run `bash docker/entrypoint.sh`, on `M1 macbook`, or the linux vm `10.211.55.13`? We don't have `M1 macbook`. However I confirm that this procedure work on `linux/amd64` and `linux/arm64`.

**on `M1 macbook`**   

- When I debug the breakpoints, it seems to be the code `spec.loader.exec_module(page)` that fails when `conversation_app.py`  is loaded。

<img width="1159" alt="image" src="https://github.com/user-attachments/assets/8aa6a9ac-5fc6-48fa-b499-23500322b2a5">

- **What can be ruled out is the inability to access the virtual machine, and this is my** `service_conf.yaml`  **file：**
```
ragflow:
  host: 127.0.0.1
  http_port: 9380
mysql:
  name: 'rag_flow'
  user: 'root'
  password: 'infini_rag_flow'
  host: '10.211.55.13'
  port: 3306
  max_connections: 100
  stale_timeout: 30
minio:
  user: 'rag_flow'
  password: 'infini_rag_flow'
  host: '10.211.55.13:9000'
es:
  hosts: 'http://10.211.55.13:9200'
  username: 'elastic'
  password: 'infini_rag_flow'
redis:
  db: 1
  password: 'infini_rag_flow'
  host: '10.211.55.13:6379'

```
