### ISSUE TITLE
[Feature Request]: Dynamically create the service_conf.yaml file by replacing environment variables from .env

### ISSUE THREAD

**Issue by gschmutz** [infiniflow/ragflow#3322]
### Is there an existing issue for the same feature request?

- [X] I have checked the existing issues.

### Is your feature request related to a problem?

Manually editing the `service_conf.yaml` file and keeping it in sync with the `.env` file could be avoided by dynamically replacing the values by the environment variables.

### Describe the feature you'd like

Instead of manually having to edit the `service_conf.yaml` file and mapping it into the docker container at runtime, a template file could be used and the values replaced by the environment variables from the `.env` file. 

```yaml
ragflow:
  host: ${RAGFLOW_HOST:-0.0.0.0}
  http_port: 9380
mysql:
  name: '${MYSQL_DBNAME:-rag_flow}'
  user: '${MYSQL_USER:-root}'
  password: '${MYSQL_PASSWORD:-infini_rag_flow}'
  host: '${MYSQL_HOST:-mysql}'
  port: 3306
  max_connections: 100
  stale_timeout: 30
...
```

This template file needs to be copied into the docker image so that it is available for the replacement.

The replacement of the env vars would be done in the `entrypoint.sh` file and the mapping of the `service_conf.yaml` file in the `docker-compose.yaml` is no longer necessary.

### Describe implementation you've considered

see description above.

I have it working locally and could submit a pull request with the changes.
