### ISSUE TITLE
[Bug]: openapi provider compatible not work

### ISSUE THREAD

**Issue by devMls** [infiniflow/ragflow#3700]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### RAGFlow workspace code commit ID

dont now

### RAGFlow image version

0.14

### Other environment information

```Markdown
docker swarm
```

### Actual behavior

provider say me that now found

![image](https://github.com/user-attachments/assets/2083ca78-ba30-438d-bea0-5c7827308a9e)

but it looks fine in open api compatible provider

![image](https://github.com/user-attachments/assets/246397ed-f3b2-4e39-b1ba-3ffee598c738)

I don't know how the compose url is mounted, but in the vllm/vllm-openai (my provider I find that):

INFO:     10.0.1.19:35092 - "POST / HTTP/1.1" 404 Not Found

INFO:     10.0.1.19:49916 - "POST / HTTP/1.1" 404 Not Found

### Steps to reproduce

```Markdown
install vllm/vllm-openai install model BAAI/bge-m3 and try to connect betwwen option of provider openai compatible
```

**Comment by KevinHuSh** [comment]
I did not get it. What's the error message poped up?

**Comment by devMls** [comment]
I think thats i have found the problem

Is posible that URL require exact URL? Https://rerank_server:8000/V1/rerank?

With this config the error i have  change, but i think thats is problem for the rerank server. Any recomendation outside vllm or localai?

**Comment by samling** [comment]
I was having the same issue; I use litellm as my model proxy for convenience and to log traces to langfuse. Other model types (embedding, chat) work fine, but adding a rerank model from the litellm endpoint wasn't working. The error message tipped me off that it was looking for a model called e.g. `rerank-english-v3.0___OpenAI-API` instead of just `rerank-english-v3.0` within litellm, so my workaround for now is to add a duplicate model with that model name, which ragflow seems to be ok with.

```
      - model_name: rerank-english-v3.0
        litellm_params:
          model: cohere/rerank-english-v3.0
          api_key: os.environ/COHERE_API_KEY
          drop_params: true

      - model_name: rerank-english-v3.0___OpenAI-API
        litellm_params:
          model: cohere/rerank-english-v3.0
          api_key: os.environ/COHERE_API_KEY
          drop_params: true
```
