### ISSUE TITLE
[Question]: Why is it so slowly?

### ISSUE THREAD

**Issue by hugyu** [infiniflow/ragflow#387]
### Describe your problem

![image](https://github.com/infiniflow/ragflow/assets/92319342/db4148d5-923f-494d-87fa-fd1325088892)
为什么解析文件很缓慢而且会失败
有时候会报出网络错误 但是网络没有问题 希望改进一下网页交互提示
还有就是多个提示框的问题
![image](https://github.com/infiniflow/ragflow/assets/92319342/0fe9968b-2900-40be-948a-6ebe8e781015)

**Comment by hugyu** [comment]
有时候会报出网络错误 但是网络没有问题 希望改进一下网页交互提示

**Comment by wzikang** [comment]
You can try calling GPU resources for parsing. According to the process of Docker deployment, GPU resources are not called by default. Here, by checking "docker/docker-compose. yml" and "docker/docker-compose-cn. yml", it can be seen that there is no configuration related to GPU during Docker container creation.

You just need to stop and delete the relevant containers that have already been started, add the following configuration in these two folders, and re execute the Docker Compose. When parsing again, you will find that the speed will be much faster after calling the GPU.

```
deploy: 
   resources:
      reservations:
         devices:
           - driver: nvidia
           device_ids: ['0']
           capabilities: [gpu]
```
Such as docker-compose. yml， complete as follows:
```
version: '2.2'
include:
  - path: ./docker-compose-base.yml
    env_file: ./.env
services:
  ragflow:
    depends_on:
      mysql:
        condition: service_healthy
      es01:
        condition: service_healthy
    image: infiniflow/ragflow:v1.0
    container_name: ragflow-server
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]
    ports:
      - ${SVR_HTTP_PORT}:9380
      - 80:80
      - 443:443
    volumes:
      - ./service_conf.yaml:/ragflow/conf/service_conf.yaml
      - ./entrypoint.sh:/ragflow/entrypoint.sh
      - ./ragflow-logs:/ragflow/logs
      - ./nginx/ragflow.conf:/etc/nginx/conf.d/ragflow.conf
      - ./nginx/proxy.conf:/etc/nginx/proxy.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    environment:
      - TZ=${TIMEZONE}
    networks:
      - ragflow
    restart: always
```
