### ISSUE TITLE
[Question]: MySQL keeps restarting

### ISSUE THREAD

**Issue by doufurua** [infiniflow/ragflow#4547]
### Describe your problem

[logs ragflow-mysql.txt](https://github.com/user-attachments/files/18475933/logs.ragflow-mysql.txt)

Here’s the translation of your request:

"I deployed Ragflow on the Unraid system using Docker Compose. After running `compose up` and starting the container, I noticed that MySQL keeps restarting, which prevents the Ragflow-server web page from registering users. The container logs are attached. I am unable to change the permissions for `init.sql` as it always reverts automatically. Please help me resolve this issue."

[logs ragflow-mysql.txt](https://github.com/user-attachments/files/18475940/logs.ragflow-mysql.txt)

<!-- Uploading "logs ragflow-mysql.txt"... --

**Comment by yuzhichang** [comment]
It's known that MySQL 8 cannot boot from existing MySQL 5.7 data.
If that's the case, you can drop existing data like this:
```
docker compose -f docker/docker-compose.yml down -v
```

Then start:
```
docker compose -f docker/docker-compose.yml up -d
```

**Comment by doufurua** [comment]
> 众所周知，MySQL 8 无法从现有的 MySQL 5.7 数据启动。 如果是这种情况，您可以像这样删除现有数据：
> 
> ```
> docker compose -f docker/docker-compose.yml down -v
> ```
> 
> 然后开始：
> 
> ```
> docker compose -f docker/docker-compose.yml up -d
> ```



> It's known that MySQL 8 cannot boot from existing MySQL 5.7 data. If that's the case, you can drop existing data like this:
> 
> ```
> docker compose -f docker/docker-compose.yml down -v
> ```
> 
> Then start:
> 
> ```
> docker compose -f docker/docker-compose.yml up -d
> ```

![Image](https://github.com/user-attachments/assets/231ba8ef-d3a2-49b4-b39e-4ad3ed86639a)
The problem remains unsolved

**Comment by tonylekhtman** [comment]
I had the problem and solved it by changing permissions of init.sql script inside docker file

```chmod 755 docker/init.sql```

another thing I did which might be not needed is updating mysql section in docker/docker-compose-base.yaml to:

```
mysql:
    # mysql:5.7 linux/arm64 image is unavailable.
    image: mysql:8.0.39
    container_name: ragflow-mysql
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - TZ=${TIMEZONE}
    command:
      --max_connections=1000
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --default-authentication-plugin=mysql_native_password
      --tls_version="TLSv1.2,TLSv1.3"
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ragflow
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-uroot", "-p${MYSQL_PASSWORD}"]
      interval: 10s
      timeout: 10s
      retries: 3
    restart: on-failure
```

difference in volumes definition and removal of init-file arg

possibly only changing permissions is sufficient
