### ISSUE TITLE
[Question]:how to set default LLM and chat models for Ragflow?

### ISSUE THREAD

**Issue by AstronautKkkkkkkk** [infiniflow/ragflow#4614]
### Describe your problem

Currently, every time a new account is created, I need to reconfigure the LLM and chat model settings. I want to add a default option to the system so that newly registered users can start using it immediately. How should I implement this? I observed that the documentation only provides API and key-based configurations, but I have local models deployed on Ollama. How can I add these?

**Comment by KevinHuSh** [comment]
Beside the configuration, you might need to refine the code here.

![Image](https://github.com/user-attachments/assets/5c6111af-c896-49c7-bd2e-3bfa08103f37)

**Comment by rplescia** [comment]
Do we need to add 'key'/'api-key': xxxxxx as one of the parameters here or must that be configured elsewhere? 

I want to do exactly this. Set the default LLM to OpenAI with the API key so that users don't have to enter the API key themselves.

**Comment by rplescia** [comment]
@KevinHuSh or @yingfeng Please see my question above. I want to know if it's possible to set up a working 'system' LLM connection with API key so that all users can use the default 'system' LLM without having to supply an API key.

Many thanks.

**Comment by KevinHuSh** [comment]
Alterations of both `conf/service_conf.yaml` and setting.py are needed, I guess.

![Image](https://github.com/user-attachments/assets/38dbf4da-a632-4079-8132-e39d2e69b485)

**Comment by rplescia** [comment]
Thanks very much!

**Comment by Odrec** [comment]
I added this settings for VLLM but it doesn't show up an added model in the Model Providers

```
user_default_llm:
  factory: 'VLLM'
  api_key: '{{ vault_secrets.vllm_api_key }}'
  base_url: 'https://vllm.virt.uos.com/v1'
  default_models:
    chat_model: 'google/gemma-3-27b-it'
    embedding_model: ''
    rerank_model: ''
    asr_model: ''
    image2text_model: ''
```

**Comment by Jonah879** [comment]
Hello, did anyone find out how to solve this? I tried changing the settings.py and the service_conf.yaml, but my models didn't show up.

**Comment by Odrec** [comment]
> Hello, did anyone find out how to solve this? I tried changing the settings.py and the service_conf.yaml, but my models didn't show up.

This is what we ended up doing to set up our Gemma 3 model as default for all users:

In service_conf.yaml

```
user_default_llm:
  factory: 'VLLM'
  api_key: '{{ vault_secrets.vllm_api_key }}'
  base_url: 'https://vllm.virt.uos.com/v1'
  default_models:
    chat_model: 'google/gemma-3-27b-it'
    # Using built-in embedding model from RAGFlow Docker image
    embedding_model: 'BAAI/bge-large-zh-v1.5' #This is one of RAGFlow's integrated embedding's model
    rerank_model: ''
    asr_model: ''
    image2text_model: ''

```

In llm_factories.json we added this entry for vLLM

```
,
        {
            "name": "VLLM",
            "logo": "",
            "tags": "LLM,TEXT EMBEDDING,SPEECH2TEXT,MODERATION",
            "status": "1",
            "llm": [
                {
                    "llm_name": "google/gemma-3-27b-it",
                    "tags": "LLM,CHAT,32K",
                    "max_tokens": 32768,
                    "model_type": "chat",
                    "is_tools": true
                }
            ]
        },
```
