### ISSUE TITLE
[Question]: http://es01:1200连接失败是怎么回事？请大神帮忙

### ISSUE THREAD

**Issue by qiulei3344** [infiniflow/ragflow#4853]
### Describe your problem

在ubuntu系统的docker里运行

```
ragflow# docker compose -f docker/docker-compose.yml up -d
[+] Running 5/5
 ✔ Container ragflow-redis   Running                                                                                                                                                                                                                                                      0.0s 
 ✔ Container ragflow-es-01   Running                                                                                                                                                                                                                                                      0.0s 
 ✔ Container ragflow-mysql   Healthy                                                                                                                                                                                                                                                      0.5s 
 ✔ Container ragflow-minio   Running                                                                                                                                                                                                                                                      0.0s 
 ✔ Container ragflow-server  Running           
```
再运行docker logs -f ragflow-server报错

```
docker logs -f ragflow-server
[WARNING] [2025-02-09 10:15:22,335] [_node_pool.mark_dead] [line:249]: Node <Urllib3HttpNode(http://es01:1200)> has failed for 1 times in a row, putting on 1 second timeout
[WARNING] [2025-02-09 10:15:22,335] [_transport.perform_request] [line:395]: Retrying request after failure (attempt 0 of 3)
Traceback (most recent call last):
  File "/ragflow/.venv/lib/python3.12/site-packages/elastic_transport/_transport.py", line 328, in perform_request
    meta, raw_data = node.perform_request(
                     ^^^^^^^^^^^^^^^^^^^^^
  File "/ragflow/.venv/lib/python3.12/site-packages/elastic_transport/_node/_http_urllib3.py", line 202, in perform_request
    raise err from None
elastic_transport.ConnectionError: Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f5466fdbce0>: Failed to establish a new connection: [Errno 111] Connection refused)
```
看了一下配置

应该没有问题呀

con/service_conf.yaml的配置
```
es:
  hosts: 'http://es01:1200'
  username: 'elastic'
  password: 'infini_rag_flow'
```

/docker/.env的配置
```
# The hostname where the Elasticsearch service is exposed
ES_HOST=es01

# The port used to expose the Elasticsearch service to the host machine, 
# allowing EXTERNAL access to the service running inside the Docker container.
ES_PORT=1200

# The password for Elasticsearch. 
ELASTIC_PASSWORD=infini_rag_flow
```

/docker/docker-compose-base.yml的配置
```
es01:
    container_name: ragflow-es-01
    profiles:
      - elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - ${ES_PORT}:9200
    env_file: .env
    environment:
      - node.name=es01
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - bootstrap.memory_lock=false
      - discovery.type=single-node
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - cluster.routing.allocation.disk.watermark.low=5gb
      - cluster.routing.allocation.disk.watermark.high=3gb
      - cluster.routing.allocation.disk.watermark.flood_stage=2gb
      - TZ=${TIMEZONE}
      - ES_JAVA_OPTS=-Xms512m -Xmx512m  # 内存限制
      - network.host=0.0.0.0  # 允许所有 IP 访问
    mem_limit: ${MEM_LIMIT}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:9200"]
      interval: 10s
      timeout: 10s
      retries: 120
    networks:
      - ragflow
    restart: on-failure
```

本地可以访问http://es01:1200返回es的版本信息，请各位大神指点一二
