### ISSUE TITLE
How to choose a different GPU for embedding in create kb phase?

### ISSUE THREAD

**Issue by Deeperfinder** [infiniflow/ragflow#4878]
### Describe your problem

if i have 8 GPUs, how to specify embedding in GPU 1?

**Comment by Deeperfinder** [comment]
Also， If I want to use multiple GPUs for embedding operations, how should I configure them?

**Comment by KevinHuSh** [comment]
Please refer to [this](https://docs.docker.com/compose/how-tos/gpu-support/).

**Comment by Deeperfinder** [comment]
> Please refer to [this](https://docs.docker.com/compose/how-tos/gpu-support/).
I built the image using docker-compose-gpu-CN-oc9.yml, and the default option here is to use all GPU, as shown below:
```
    restart: on-failure
    # https://docs.docker.com/engine/daemon/prometheus/#create-a-prometheus-configuration
    # If you're using Docker Desktop, the --add-host flag is optional. This flag makes sure that the host's internal IP gets exposed to the Prometheus container.
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

```
