### ISSUE TITLE
How to change the storage disk which are used to be tmp when running ragflow?

### ISSUE THREAD

**Issue by Deeperfinder** [infiniflow/ragflow#4891]
### Describe your problem

> Greater than or equal to 50GB, used to store various types of data generated during RagFlow operation, including but not limited to log files, temporary data files, and possible database files.

If my root directory only has **30GB,** but my other disks such as **/nfs/** have 1TB of storage space, how can I specify that all kinds of data generated during the running process be stored on/nfs?

**Comment by beatmaus** [comment]
https://www.cnblogs.com/zhaodalei/p/18460800

**Comment by Deeperfinder** [comment]
![Image](https://github.com/user-attachments/assets/0625dff8-5807-4ad4-a2a9-f1c4986d8fa9)
my docker storage in  /var/lib/docker,  so this is enough for images to run, but i see whe ragflow is running, the **root dir ( / )** space will growth untill fulling .

**Comment by Yannnnnnny** [comment]
You can change the storage location by modifying the volume mappings in the Docker Compose configuration.

For example, you can bind the persistent data directories to `/nfs`:

```yaml
services:
  es01:
    volumes:
      - /nfs/ragflow/elasticsearch:/usr/share/elasticsearch/data

  mysql:
    volumes:
      - /nfs/ragflow/mysql:/var/lib/mysql

  minio:
    volumes:
      - /nfs/ragflow/minio:/data
```

For RAGFlow logs, you can also change:

```yaml
- ./ragflow-logs:/ragflow/logs
```

to:

```yaml
- /nfs/ragflow/logs:/ragflow/logs
```

Please note that the 50 GB disk requirement does not necessarily mean that the root partition itself must have 50 GB available. You can use another disk for persistent data through Docker volume mappings.

If you already have an existing RAGFlow deployment with data, make sure to migrate the existing volume data before changing the mappings to avoid data loss.
