### ISSUE TITLE
[Feature Request]: user_default_llm supports to configure different model factory for each type model

### ISSUE THREAD

**Issue by Colstuwjx** [infiniflow/ragflow#8061]
### Self Checks

- [x] I have searched for existing issues [search for existing issues](https://github.com/infiniflow/ragflow/issues), including closed ones.
- [x] I confirm that I am using English to submit this report ([Language Policy](https://github.com/infiniflow/ragflow/issues/5910)).
- [x] Non-english title submitions will be closed directly ( 非英文标题的提交将会被直接关闭 ) ([Language Policy](https://github.com/infiniflow/ragflow/issues/5910)).
- [x] Please do not modify this template :) and fill in all the required fields.

### Is your feature request related to a problem?

```Markdown
Currently, it seems like the user_default_llm would ONLY support one single model factory to provide multiple models, e.g. QWen to provide both chat model, embedding model, rerank model etc. It would be great if we could support to configure different model factory for each type model.
```

### Describe the feature you'd like

Configure different model factory for each type model in the service config yaml so that the new sign-up users would have these default llm models to use.

### Describe implementation you've considered

like this ?

```
user_default_llm:
   chat_model:
     model: 'qwen-plus'
     factory: 'Tongyi-Qianwen'
     api_key: 'sk-xxxxxxxxxxxxx'
     base_url: 'xxx'
     max_tokens: 65536
  embedding_model:
     model: 'BAAI/bge-large-...'
     factory: 'Tongyi-Qianwen'
     api_key: 'sk-xxxxxxxxxxxxx'
     base_url: 'xxx'
     max_tokens: 65536
  ...
```

### Documentation, adoption, use case

```Markdown

```
