### ISSUE TITLE
[Bug]: error mcp prot

### ISSUE THREAD

**Issue by bulolo** [infiniflow/ragflow#8561]
### Self Checks

- [x] I have searched for existing issues [search for existing issues](https://github.com/infiniflow/ragflow/issues), including closed ones.
- [x] I confirm that I am using English to submit this report ([Language Policy](https://github.com/infiniflow/ragflow/issues/5910)).
- [x] Non-english title submitions will be closed directly ( 非英文标题的提交将会被直接关闭 ) ([Language Policy](https://github.com/infiniflow/ragflow/issues/5910)).
- [x] Please do not modify this template :) and fill in all the required fields.

### RAGFlow workspace code commit ID

?

### RAGFlow image version

1.19.1

### Other environment information

```Markdown

```

### Actual behavior

```
Starting ragflow_server...
Starting MCP Server on 0.0.0.0:9382 with base URL http://127.0.0.1:9380...
Starting 1 task executor(s) on host 'ragflow-56d6d79594-t2zrc'...
2025-06-28 17:26:37,574 INFO     26 ragflow_server log path: /ragflow/logs/ragflow_server.log, log levels: {'peewee': 'WARNING', 'pdfminer': 'WARNING', 'root': 'INFO'}

__  __  ____ ____       ____  _____ ______     _______ ____
|  \/  |/ ___|  _ \     / ___|| ____|  _ \ \   / / ____|  _ \
| |\/| | |   | |_) |    \___ \|  _| | |_) \ \ / /|  _| | |_) |
| |  | | |___|  __/      ___) | |___|  _ < \ V / | |___|  _ <
|_|  |_|\____|_|        |____/|_____|_| \_\ \_/  |_____|_| \_\

MCP launch mode: self-host
MCP host: 0.0.0.0
MCP port: tcp://10.1.125.65:9382. ------> wrong
MCP base_url: http://127.0.0.1:9380
Traceback (most recent call last):
  File "/ragflow/mcp/server/server.py", line 307, in <module>
    port=int(PORT),
ValueError: invalid literal for int() with base 10: 'tcp://10.1.125.65:9382'
```

### Steps to reproduce

```Markdown
helm on k8s


      containers:
      - name: ragflow
        image: {{ .Values.env.RAGFLOW_IMAGE }}
        args:
          - --enable-mcpserver
          - --mcp-host=0.0.0.0
          - --mcp-port=9382
          - --mcp-base-url=http://127.0.0.1:9380
          - --mcp-script-path=/ragflow/mcp/server/server.py
          - --mcp-mode=self-host
          - --mcp-host-api-key=ragflow-xxx
```

**Comment by bulolo** [comment]
```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ragflow.fullname" . }}
  labels:
    {{- include "ragflow.labels" . | nindent 4 }}
    app.kubernetes.io/component: ragflow
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "ragflow.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: ragflow
  {{- with .Values.ragflow.deployment.strategy }}
  strategy:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "ragflow.labels" . | nindent 8 }}
        app.kubernetes.io/component: ragflow
      annotations:
        checksum/config-env: {{ include (print $.Template.BasePath "/env.yaml") . | sha256sum }}
        checksum/config-ragflow: {{ include (print $.Template.BasePath "/ragflow_config.yaml") . | sha256sum }}
    spec:
      {{- if .Values.nodeSelector }}
      nodeSelector: {{- .Values.nodeSelector | toYaml | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: ragflow
        image: {{ .Values.env.RAGFLOW_IMAGE }}
        args:
          - --enable-mcpserver
          - --mcp-host=0.0.0.0
          - --mcp-port=9382
          - --mcp-base-url=http://127.0.0.1:9380
          - --mcp-script-path=/ragflow/mcp/server/server.py
          - --mcp-mode=self-host
          - --mcp-host-api-key=ragflow-XXX
        ports:
          - containerPort: 80
            name: http
          - containerPort: 9380
            name: http-api
          - containerPort: 9382
            name: mcp
        volumeMounts:
          - mountPath: /etc/nginx/conf.d/ragflow.conf
            subPath: ragflow.conf
            name: nginx-config-volume
          - mountPath: /etc/nginx/proxy.conf
            subPath: proxy.conf
            name: nginx-config-volume
          - mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
            name: nginx-config-volume
        envFrom:
          - secretRef:
              name: {{ include "ragflow.fullname" . }}-env-config
        {{- with .Values.ragflow.deployment.resources }}
        resources:
          {{- . | toYaml | nindent 10 }}
        {{- end }}
      volumes:
        - name: nginx-config-volume
          configMap:
            name: nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ragflow.fullname" . }}
  labels:
    {{- include "ragflow.labels" . | nindent 4 }}
    app.kubernetes.io/component: ragflow
spec:
  selector:
    {{- include "ragflow.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ragflow
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
      name: http
  type: {{ .Values.ragflow.service.type }}
---
{{- if .Values.ragflow.api.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api
  labels:
    {{- include "ragflow.labels" . | nindent 4 }}
    app.kubernetes.io/component: ragflow
spec:
  selector:
    {{- include "ragflow.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ragflow
  ports:
    - protocol: TCP
      port: 80
      targetPort: http-api
      name: http-api
  type: {{ .Values.ragflow.api.service.type }}
{{- end }}
---
{{- if .Values.ragflow.mcp.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mcp
  labels:
    {{- include "ragflow.labels" . | nindent 4 }}
    app.kubernetes.io/component: ragflow
spec:
  selector:
    {{- include "ragflow.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ragflow
  ports:
    - protocol: TCP
      port: 9382
      targetPort: mcp
      name: mcp
  type: {{ .Values.ragflow.api.service.type }}
{{- end }}
```

i add the mcp command on this ,we can see it is right set on mcp-port
```
        args:
          - --enable-mcpserver
          - --mcp-host=0.0.0.0
          - --mcp-port=9382
          - --mcp-base-url=http://127.0.0.1:9380
          - --mcp-script-path=/ragflow/mcp/server/server.py
          - --mcp-mode=self-host
          - --mcp-host-api-key=ragflow-XXX
```

i edit the helm file https://github.com/infiniflow/ragflow/blob/main/helm/templates/ragflow.yaml#L30

@dosu
